amzustory6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('addKegiatan/', views.addKegiatan, name='addKegiatan'),
    path('addPeserta/<int:id>', views.addPeserta, name='addPeserta')
]

main/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan = models.CharField('Nama Kegiatan', max_length = 50)
    desc_kegiatan = models.TextField('Deskripsi', blank=True)

    def __str__(self):
        return self.nama_kegiatan

class Peserta(models.Model):
    nama_peserta = models.CharField('Nama', max_length = 30)
    kegiatan = models.ForeignKey('Kegiatan', on_delete=models.CASCADE)

    def __str__(self):
        return self.nama_peserta

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import Kegiatan, Peserta

class KegiatanForm(ModelForm):
    class Meta:
        model = Kegiatan
        fields = "__all__"

class PesertaForm(ModelForm):
    class Meta:
        model = Peserta
        fields = ['nama_peserta']

main/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Peserta
from .forms import KegiatanForm, PesertaForm


def home(request):
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    context = {'peserta' : peserta, 'kegiatan' : kegiatan}
    return render(request, 'main/home.html', context)

def addKegiatan(request):
    if request.method == 'POST':
        form = KegiatanForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('main:home')
    
    else:
        form = KegiatanForm()
    
    context = {'form' : form}
    return render(request, 'main/addKegiatan.html', context)

def addPeserta(request, id):
    if request.method == 'POST':
        form = PesertaForm(request.POST)

        if form.is_valid():
            form = Peserta(kegiatan = Kegiatan.objects.get(id=id), nama_peserta = form.data['nama_peserta'])
            form.save()
            return redirect('main:home')
    
    else:
        form = PesertaForm()
    
    context = {'form' : form}
    return render(request, 'main/addPeserta.html', context)

main/templates/main/addKegiatan.html
{% extends 'base.html' %}
{$ load static %}
{% block meta %}
    <title>Add Kegiatan</title>
{% endblock meta %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <form class="form-control" action="#" method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <button type="submit" class="btn btn-outline-success btn-block">Add</button>
        </form>
    </div>
</div>
    
    
{% endblock content %}

main/templates/main/addPeserta.html
{% extends 'base.html' %}
{$ load static %}
{% block meta %}
    <title>Add Peserta</title>
{% endblock meta %}
{% block content %}




<div class="container mt-5">
    <div class="row">
        <div class="col text-center">
            <h2>Form Peserta</h2>
        </div>
    </div>

    <div class="row mt-5">
        <form action="#" method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <input type="submit" value="Submit">
        </form>
    </div>
</div>

    
    
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kegiatan</title>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
  {% for x in kegiatan %}
  <table class="table table-borderless text-center">
    <tr>
      <th>Kegiatan</th>
    </tr>
    <tr>
      <td>{{x.nama_kegiatan}}</td>
    </tr> 
    <tr>
      <th>Deskripsi</th>
    </tr>
    <tr>
      <td>{{x.desc_kegiatan}}</td>
    </tr>     
    <tr>
      <th>Peserta</th>
    </tr> 
    {% for y in peserta %}
      {% if y.kegiatan == x %} 
    <tr>
      <td>{{y.nama_peserta}}</td>
    </tr>
    {% endif %}
      {% endfor %}
  </table>

  <div class="row">
    <div class="col text-center">
          <a class="btn btn-outline-success btn-block" href="{% url 'main:addPeserta' x.id %}">Add Peserta</a>
    </div>
  </div>
{% endfor %}
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

 <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
    {% block meta %}
    {% endblock meta %}
  </head>
  <body class="mt-5">

    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="addKegiatan">Add Kegiatan</a>
        </div>
      </div>
    </nav>
      {% block content %}
      {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>